"""empty message

Revision ID: 86da9bc549d3
Revises: bb530f0354c4
Create Date: 2025-06-15 13:16:42.640238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86da9bc549d3'
down_revision = 'bb530f0354c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False))
        batch_op.drop_column('icons')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icons', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
