version: '3'
services:
  llmops-ui:
    image: llmops-ui:0.1.0
    build:
      context: ../ui
      dockerfile: Dockerfile
    container_name: llmops-ui
    restart: always
    environment: [ ]
    ports:
      - "3000:3000"
  llmops-api:
    image: llmops-api:0.1.0
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: llmops-api
    restart: always
    volumes:
      - ./volumes/app/storage:/app/api/storage
    environment:
      # 模式为API，代表启用API服务
      MODE: api
      SERVER_WORKER_AMOUNT: 4
      SERVER_THREAD_AMOUNT: 4
      # 数据库迁移配置
      MIGRATION_ENABLED: 'true'
      # JWT加密秘钥
      JWT_SECRET_KEY:
      # 服务配置 - 修改为您的IP地址
      SERVICE_IP: 
      SERVICE_API_PREFIX: 
      # CSRF校验开关
      WTF_CSRF_ENABLED: 'false'
      # SQLAlchemy数据库配置
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:llmops123456@llmops-db:5432/llmops?client_encoding=utf8
      SQLALCHEMY_POOL_SIZE: 30
      SQLALCHEMY_POOL_RECYCLE: 3600
      SQLALCHEMY_ECHO: 'true'
      # Redis缓存数据库配置
      REDIS_HOST: llmops-redis
      REDIS_PORT: 6379
      REDIS_USERNAME: ''
      REDIS_PASSWORD: ''
      REDIS_DB: 0
      REDIS_USE_SSL: 'false'
      # Weaviate向量数据库配置
      WEAVIATE_HTTP_HOST: llmops-weaviate
      WEAVIATE_HTTP_PORT: 8080
      WEAVIATE_GRPC_HOST: llmops-weaviate
      WEAVIATE_GRPC_PORT: 50051
      WEAVIATE_API_KEY: ftBC9hKkjfdbdi0wW3T6kEtMh5BZFpGa1DF8
      # 腾讯云COS对象存储
      COS_SECRET_ID: 
      COS_SECRET_KEY: 
      COS_REGION: 
      COS_SCHEME: 
      COS_BUCKET: 
      COS_DOMAIN: 
      # Celery异步队列任务配置
      CELERY_BROKER_DB: 1
      CELERY_RESULT_BACKEND_DB: 1
      CELERY_TASK_IGNORE_RESULT: 'true'
      CELERY_RESULT_EXPIRES: 3600
      CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP: 'true'
      # Github OAuth应用秘钥 - 由于无法使用域名，这些配置可能需要调整
      GITHUB_CLIENT_ID:
      GITHUB_CLIENT_SECRET: 
      GITHUB_REDIRECT_URI: 
      # LangSmith配置
      LANGSMITH_TRACING: 'true'
      LANGSMITH_ENDPOINT: https://api.smith.langchain.com
      LANGSMITH_API_KEY: 
      LANGSMITH_PROJECT:
        # HuggingFace配置
      TRANSFORMERS_OFFLINE: 0
      # 辅助Agent智能体应用id标识
      ASSISTANT_AGENT_ID: f47ac10b-58cc-4372-a567-0e02b2c3d479
      # OpenAI服务提供者
      OPENAI_API_KEY:
      OPENAI_BASE_URL: 
      # DeepSeek服务提供者
      DEEPSEEK_API_KEY: 
      DEEPSEEK_API_BASE:
      # 百度千帆服务提供者
      qianfan_ak: 
      qianfan_sk: 
      # 月之暗面服务提供者
      MOONSHOT_API_KEY: 
      # 通义千问服务提供者
      DASHSCOPE_API_KEY: 
      DASHSCOPE_BASE_URL: 
      # 高德工具API秘钥
      GAODE_API_KEY: 
      # 谷歌Serper搜索API秘钥
      SERPER_API_KEY:
    ports:
      - "5001:5001"
    depends_on:
      - llmops-db
      - llmops-redis
      - llmops-weaviate
  llmops-celery:
    image: llmops-api:0.1.0
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: llmops-celery
    restart: always
    volumes:
      - ./volumes/app/storage:/app/api/storage
    environment:
      # 模式为celery，代表启用Celery异步任务队列
      MODE: celery
      CELERY_WORKER_AMOUNT: 4
      # 数据库迁移配置
      MIGRATION_ENABLED: 'false'
      # 服务配置 - 修改为您的IP地址
      SERVICE_IP: 
      SERVICE_API_PREFIX: 
      # JWT加密秘钥
      JWT_SECRET_KEY: 
      # CSRF校验开关
      WTF_CSRF_ENABLED: 'false'
      # SQLAlchemy数据库配置
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:llmops123456@llmops-db:5432/llmops?client_encoding=utf8
      SQLALCHEMY_POOL_SIZE: 30
      SQLALCHEMY_POOL_RECYCLE: 3600
      SQLALCHEMY_ECHO: 'true'
      # Redis缓存数据库配置
      REDIS_HOST: llmops-redis
      REDIS_PORT: 6379
      REDIS_USERNAME: ''
      REDIS_PASSWORD: ''
      REDIS_DB: 0
      REDIS_USE_SSL: 'false'
      # Weaviate向量数据库配置
      WEAVIATE_HTTP_HOST: llmops-weaviate
      WEAVIATE_HTTP_PORT: 8080
      WEAVIATE_GRPC_HOST: llmops-weaviate
      WEAVIATE_GRPC_PORT: 50051
      WEAVIATE_API_KEY: ftBC9hKkjfdbdi0wW3T6kEtMh5BZFpGa1DF8
      # 腾讯云COS对象存储
      COS_SECRET_ID: 
      COS_SECRET_KEY: 
      COS_REGION: 
      COS_SCHEME: 
      COS_BUCKET: 
      COS_DOMAIN: 
      # Celery异步队列任务配置
      CELERY_BROKER_DB: 1
      CELERY_RESULT_BACKEND_DB: 1
      CELERY_TASK_IGNORE_RESULT: 'true'
      CELERY_RESULT_EXPIRES: 3600
      CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP: 'true'
      # Github OAuth应用秘钥 - 由于无法使用域名，这些配置可能需要调整
      GITHUB_CLIENT_ID: 
      GITHUB_CLIENT_SECRET: 
      GITHUB_REDIRECT_URI: 
      # LangSmith配置
      LANGSMITH_TRACING:  'true'
      LANGSMITH_ENDPOINT:  https://api.smith.langchain.com
      LANGSMITH_API_KEY: 
      LANGSMITH_PROJECT:
      # HuggingFace配置
      TRANSFORMERS_OFFLINE: 0
      # 辅助Agent智能体应用id标识
      ASSISTANT_AGENT_ID: f47ac10b-58cc-4372-a567-0e02b2c3d479
      # OpenAI服务提供者
      OPENAI_API_KEY: 
      OPENAI_API_BASE: 
      # DeepSeek服务提供者
      DEEPSEEK_API_KEY: 
      DEEPSEEK_API_BASE:
      # 百度千帆服务提供者
      qianfan_ak: 
      qianfan_sk: 
      # 月之暗面服务提供者
      MOONSHOT_API_KEY: 
      # 通义千问服务提供者
      DASHSCOPE_API_KEY: 
      DASHSCOPE_API_BASE:
      # 高德工具API秘钥
      GAODE_API_KEY: 
      # 谷歌Serper搜索API秘钥
      SERPER_API_KEY: 
    depends_on:
      - llmops-db
      - llmops-redis
      - llmops-weaviate
  llmops-redis:
    image: redis:6-alpine
    restart: always
    container_name: llmops-redis
    volumes:
      - ./volumes/redis/data:/data
    # 启动redis服务时配置
    command: redis-server 
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    ports:
      - "6379:6379"
  llmops-db:
    image: postgres:15-alpine
    restart: always
    container_name: llmops-db
    environment:
      # 配置默认的账户名、账户密码、默认数据库、数据存储的位置
      PGUSER: postgres
      POSTGRES_PASSWORD: llmops123456
      POSTGRES_DB: llmops
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # 将postgres数据挂载到本地./volumes/db/data上
      - ./volumes/db/data:/var/lib/postgresql/data/pgdata
      # 初始化脚本只有在空数据挂载的情况下才会触发执行(.sql/.sh等)，如果已经存在数据则不会执行
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      # 每隔1s发起一个健康测试，最多重试30次
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - "5432:5432"
  llmops-weaviate:
    image: semitechnologies/weaviate:1.28.4
    container_name: llmops-weaviate
    restart: always
    environment:
      QUERY_DEFAULTS_LIMIT: 25  # 查询默认返回的数据条数
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'  # 需要授权才能和weaviate进行交互
      PERSISTENCE_DATA_PATH: /var/lib/weaviate  # weaviate数据存储路径
      DEFAULT_VECTORIZER_MODULE: 'none'  # 向量化模块设置为none
      CLUSTER_HOSTNAME: 'node1'  # 节点的主机名字
      AUTHENTICATION_APIKEY_ENABLED: 'true'  # 启动基于API秘钥的身份校验
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'ftBC9hKkjfdbdi0wW3T6kEtMh5BZFpGa1DF8'  # 允许的API秘钥列表
      AUTHENTICATION_APIKEY_USERS: 'llmops@imooc.com'  # 基于秘钥的API身份列表
      AUTHORIZATION_ADMINLIST_ENABLED: 'true'  # 启动AdminList授权方案
      AUTHORIZATION_ADMINLIST_USERS: 'llmops@imooc.com'  # 使用AdminList方案时具有管理权限的用户
    volumes:
      - ./volumes/weaviate:/var/lib/weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
  llmops-nginx:
    image: nginx:latest
    restart: always
    container_name: llmops-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/ssl
    depends_on:
      - llmops-ui
      - llmops-api
    ports:
      - "80:80"
      - "443:443"
