# 使用unstructure:0.13.7作为基础镜像(Python 3.10.13, 操作系统为Centos)
FROM downloads.unstructured.io/unstructured-io/unstructured:0.14.0 AS base

# 将requirements.txt拷贝到根目录下
COPY requirements.txt .

# 构建缓存并使用pip安装严格版本的requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt

# 二阶段生产环境构建
FROM base AS production

# 设置工作目录
WORKDIR /app/api

# 设置用户为root
USER root

# 定义环境变量
ENV FLASK_APP=app/http/app.py
ENV FLASK_ENV=production
ENV FLASK_DEBUG=0
ENV NLTK_DATA=/app/api/internal/core/unstructured/nltk_data
ENV HF_ENDPOINT=https://hf-mirror.com

# 设置容器时区为中国标准时间，避免时区错误
ENV TZ Asia/Shanghai

# 拷贝第三方依赖包+源码文件
COPY . /app/api

# 设置环境变量确保可执行文件路径在PATH中
ENV PATH="/home/notebook-user/.local/bin:${PATH}"

# 拷贝运行脚本并设置权限
COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# 暴露5001端口
EXPOSE 5001

# 运行脚本并启动项目
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]